//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoDispatcherView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoDispatcherView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string browseHtmlTemplateButton_Text_en {
            get {
                return ResourceManager.GetString("browseHtmlTemplateButton.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfoglia.
        /// </summary>
        internal static string browseHtmlTemplateButton_Text_it {
            get {
                return ResourceManager.GetString("browseHtmlTemplateButton.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string BrowsePhotosButton_Text_en {
            get {
                return ResourceManager.GetString("BrowsePhotosButton.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfoglia.
        /// </summary>
        internal static string BrowsePhotosButton_Text_it {
            get {
                return ResourceManager.GetString("BrowsePhotosButton.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string button2_Text_en {
            get {
                return ResourceManager.GetString("button2.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfoglia.
        /// </summary>
        internal static string button2_Text_it {
            get {
                return ResourceManager.GetString("button2.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File Path.
        /// </summary>
        internal static string csvFilePathLabel_Text_en {
            get {
                return ResourceManager.GetString("csvFilePathLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorso del file CSV.
        /// </summary>
        internal static string csvFilePathLabel_Text_it {
            get {
                return ResourceManager.GetString("csvFilePathLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the CSV file containing email mappings..
        /// </summary>
        internal static string csvFilePathLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("csvFilePathLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il percorso del file CSV contenente le mappature delle email..
        /// </summary>
        internal static string csvFilePathLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("csvFilePathLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Body.
        /// </summary>
        internal static string emailBodyLabel_Text_en {
            get {
                return ResourceManager.GetString("emailBodyLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpo dell&apos;email.
        /// </summary>
        internal static string emailBodyLabel_Text_it {
            get {
                return ResourceManager.GetString("emailBodyLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body text of the email..
        /// </summary>
        internal static string emailBodyLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("emailBodyLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il testo del corpo dell&apos;email..
        /// </summary>
        internal static string emailBodyLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("emailBodyLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Delay Seconds.
        /// </summary>
        internal static string emailDelaySecondsLabel_Text_en {
            get {
                return ResourceManager.GetString("emailDelaySecondsLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ritardo Invio (sec).
        /// </summary>
        internal static string emailDelaySecondsLabel_Text_it {
            get {
                return ResourceManager.GetString("emailDelaySecondsLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the delay in seconds between sending each email..
        /// </summary>
        internal static string emailDelaySecondsLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("emailDelaySecondsLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifica il ritardo in secondi tra l&apos;invio di ogni email..
        /// </summary>
        internal static string emailDelaySecondsLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("emailDelaySecondsLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Retry Attempts.
        /// </summary>
        internal static string emailRetryAttemptsLabel_Text_en {
            get {
                return ResourceManager.GetString("emailRetryAttemptsLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Tentativi Reinvio Email.
        /// </summary>
        internal static string emailRetryAttemptsLabel_Text_it {
            get {
                return ResourceManager.GetString("emailRetryAttemptsLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the maximum number of retry attempts for sending failed emails..
        /// </summary>
        internal static string emailRetryAttemptsLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("emailRetryAttemptsLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifica il numero massimo di tentativi di invio per email fallite..
        /// </summary>
        internal static string emailRetryAttemptsLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("emailRetryAttemptsLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Subject.
        /// </summary>
        internal static string emailSubjectLabel_Text_en {
            get {
                return ResourceManager.GetString("emailSubjectLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oggetto dell&apos;email.
        /// </summary>
        internal static string emailSubjectLabel_Text_it {
            get {
                return ResourceManager.GetString("emailSubjectLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subject line of the email..
        /// </summary>
        internal static string emailSubjectLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("emailSubjectLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La riga dell&apos;oggetto dell&apos;email..
        /// </summary>
        internal static string emailSubjectLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("emailSubjectLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a Feedback.
        /// </summary>
        internal static string feedbackLabel_Text_en {
            get {
                return ResourceManager.GetString("feedbackLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lascia un Feedback.
        /// </summary>
        internal static string feedbackLabel_Text_it {
            get {
                return ResourceManager.GetString("feedbackLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name.
        /// </summary>
        internal static string fromNameLabel_Text_en {
            get {
                return ResourceManager.GetString("fromNameLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome del mittente.
        /// </summary>
        internal static string fromNameLabel_Text_it {
            get {
                return ResourceManager.GetString("fromNameLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The displayed name of the email sender..
        /// </summary>
        internal static string fromNameLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("fromNameLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il nome visualizzato del mittente dell&apos;email..
        /// </summary>
        internal static string fromNameLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("fromNameLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Template Path.
        /// </summary>
        internal static string htmlTemplatePathLabel_Text_en {
            get {
                return ResourceManager.GetString("htmlTemplatePathLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorso Template HTML.
        /// </summary>
        internal static string htmlTemplatePathLabel_Text_it {
            get {
                return ResourceManager.GetString("htmlTemplatePathLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the path to the HTML template for emails..
        /// </summary>
        internal static string htmlTemplatePathLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("htmlTemplatePathLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifica il percorso del template HTML per le email..
        /// </summary>
        internal static string htmlTemplatePathLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("htmlTemplatePathLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Service Settings.
        /// </summary>
        internal static string label10_Text_en {
            get {
                return ResourceManager.GetString("label10.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni del servizio email.
        /// </summary>
        internal static string label10_Text_it {
            get {
                return ResourceManager.GetString("label10.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languageLabel_Text_en {
            get {
                return ResourceManager.GetString("languageLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        internal static string languageLabel_Text_it {
            get {
                return ResourceManager.GetString("languageLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos Directory.
        /// </summary>
        internal static string photosDirectoryLabel_Text_en {
            get {
                return ResourceManager.GetString("photosDirectoryLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory delle foto.
        /// </summary>
        internal static string photosDirectoryLabel_Text_it {
            get {
                return ResourceManager.GetString("photosDirectoryLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory where photos are stored..
        /// </summary>
        internal static string photosDirectoryLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("photosDirectoryLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La directory in cui sono archiviate le foto..
        /// </summary>
        internal static string photosDirectoryLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("photosDirectoryLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton_Text_en {
            get {
                return ResourceManager.GetString("SaveButton.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        internal static string SaveButton_Text_it {
            get {
                return ResourceManager.GetString("SaveButton.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Password.
        /// </summary>
        internal static string smtpPassLabel_Text_en {
            get {
                return ResourceManager.GetString("smtpPassLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password SMTP.
        /// </summary>
        internal static string smtpPassLabel_Text_it {
            get {
                return ResourceManager.GetString("smtpPassLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email account password..
        /// </summary>
        internal static string smtpPassLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("smtpPassLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La password dell&apos;account email..
        /// </summary>
        internal static string smtpPassLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("smtpPassLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Port.
        /// </summary>
        internal static string smtpPortLabel_Text_en {
            get {
                return ResourceManager.GetString("smtpPortLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porta SMTP.
        /// </summary>
        internal static string smtpPortLabel_Text_it {
            get {
                return ResourceManager.GetString("smtpPortLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port number used for the SMTP server..
        /// </summary>
        internal static string smtpPortLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("smtpPortLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il numero di porta utilizzato per il server SMTP..
        /// </summary>
        internal static string smtpPortLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("smtpPortLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server.
        /// </summary>
        internal static string smtpServerLabel_Text_en {
            get {
                return ResourceManager.GetString("smtpServerLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server SMTP.
        /// </summary>
        internal static string smtpServerLabel_Text_it {
            get {
                return ResourceManager.GetString("smtpServerLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address of the SMTP server..
        /// </summary>
        internal static string smtpServerLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("smtpServerLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;indirizzo del server SMTP..
        /// </summary>
        internal static string smtpServerLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("smtpServerLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Email.
        /// </summary>
        internal static string smtpUserLabel_Text_en {
            get {
                return ResourceManager.GetString("smtpUserLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email SMTP.
        /// </summary>
        internal static string smtpUserLabel_Text_it {
            get {
                return ResourceManager.GetString("smtpUserLabel.Text.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address of the account..
        /// </summary>
        internal static string smtpUserLabel_ToolTip_en {
            get {
                return ResourceManager.GetString("smtpUserLabel.ToolTip.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;indirizzo email dell&apos;account..
        /// </summary>
        internal static string smtpUserLabel_ToolTip_it {
            get {
                return ResourceManager.GetString("smtpUserLabel.ToolTip.it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Support.
        /// </summary>
        internal static string supportLabel_Text_en {
            get {
                return ResourceManager.GetString("supportLabel.Text.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporto Tecnico.
        /// </summary>
        internal static string supportLabel_Text_it {
            get {
                return ResourceManager.GetString("supportLabel.Text.it", resourceCulture);
            }
        }
    }
}
